---
- name: Install dotfiles
  hosts: all

  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      state: directory
    loop:
    - ~/.config
    - ~/.config/nvim
    - ~/.ssh

  - name: Get ~/.zshrc file stat
    stat:
      path: ~/.zshrc
    register: zshrc_stat

  - name: Remove ~/.zshrc if it's not a link
    file:
      path: ~/.zshrc
      state: absent
    when: zshrc_stat.stat.islnk is not defined or not zshrc_stat.stat.islnk

  - name: Create links
    file:
      src: "{{ playbook_dir }}/{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
    - { src: 'vimrc', dest: '~/.vimrc' }
    - { src: 'zshrc', dest: '~/.zshrc' }
    - { src: 'init.vim', dest: '~/.config/nvim/init.vim' }
    - { src: 'ssh-agent.sh', dest: '~/.ssh-agent.sh' }
    - { src: 'screenrc', dest: '~/.screenrc' }
    - { src: 'tmux.conf', dest: '~/.tmux.conf' }
    - { src: 'gitconfig', dest: '~/.gitconfig' }
    - { src: 'gdbinit', dest: '~/.gdbinit' }
    - { src: 'robbyrussell.zsh-theme', dest: '~/.oh-my-zsh/custom/themes/robbyrussell.zsh-theme' }
    - { src: 'p10k.zsh', dest: '~/.p10k.zsh' }
