# Load shared settings from base tmux config
source-file ~/.tmux.conf

# PowerShell-specific settings
set -as terminal-features ",xterm-256color:osc7"

set -g default-command "cd $(pwsh.exe -c 'Write-Host -NoNewLine \$env:userprofile' | xargs -0 wslpath); exec pwsh.exe --nologo"
set-window-option -g automatic-rename off
bind c new-window -c "#{pane_current_path}" -n "PowerShell" "exec pwsh.exe --nologo"
bind '"' split-window -v -c "#{pane_current_path}" "exec pwsh.exe --nologo"
bind % split-window -h -c "#{pane_current_path}" "exec pwsh.exe --nologo"

# Give this tmux a "PowerShell blue" color to differentiate it
set -g status-bg cyan