set -sg escape-time 10
set -g mouse on
set -g default-terminal "xterm-256color"
set-window-option -g mode-keys vi

set -g default-command "cd $(pwsh.exe -c 'Write-Host -NoNewLine \$env:userprofile' | xargs -0 wslpath); exec pwsh.exe --nologo"
set-window-option -g automatic-rename off
bind c new-window -n "PowerShell"

# Give this tmux a "PowerShell blue" color to differentiate it
set -g status-bg cyan

# Use UTF8
set -qg utf8
set-window-option -qg utf8 on

# Recommended, to avoid the Ctrl+B finger-gymnastics
# Change default prefix to Screen's
#unbind C-b
#set-option -g prefix C-a
#bind-key C-a send-prefix
#bind-key -n C-b send-prefix
#bind C-a last-window

# Optional
# split panes using - and |
#bind | split-window -h
#bind - split-window -v
#unbind '"'
#unbind %

set -g history-limit 10000
