set -sg escape-time 10
set -g mouse on
set -g default-terminal "xterm-256color"
set-window-option -g mode-keys vi

# Use UTF8
set -qg utf8
set-window-option -qg utf8 on

# Use Ctrl+Space as prefix instead of Ctrl+B
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
bind C-Space last-window

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# switch panes using Alt+<VIM binding> without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# switch windows using Alt-n/Alt-p without prefix
bind -n M-n next-window
bind -n M-p previous-window

# faster zoom
bind -n M-z resize-pane -Z

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

set -g history-limit 10000
